DROP TABLE Developers;
DROP TABLE Games;
DROP TABLE Customers;

DROP TYPE purchased_game_table;
DROP TYPE purchased_game_t;

DROP TYPE dev_table;
DROP TYPE dev_id;

--Everything needed for customers
CREATE TYPE purchased_game_t AS OBJECT (asin CHAR(10), quantity INTEGER, cost DECIMAL(7,2))
/
CREATE TYPE purchased_game_table AS TABLE OF purchased_game_t
/

CREATE TABLE Customers (
	id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	account purchased_game_table
)
NESTED TABLE account STORE AS customer_account RETURN AS LOCATOR
/


--Everything needed for developers

CREATE TABLE Developers (
	id NUMBER(10) GENERATED AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL
)
/


--Everything needed for games
CREATE TYPE dev_id AS OBJECT(id number(10))
/
CREATE TYPE dev_table AS TABLE OF dev_id
/

CREATE TABLE Games (
	asin CHAR(10) PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	price DECIMAL(5,2) NOT NULL,
	developers dev_table,
	CONSTRAINT price_geq_zero CHECK(price >= 0.0)
)
NESTED TABLE developers STORE AS game_devs RETURN AS LOCATOR
/
